default: &default
  adapter: sqlite3
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: db/league_development.sqlite3

test:
  <<: *default
  database: db/league_test.sqlite3

production:
  <<: *default
  database: db/league_production.sqlite3
